### ISSUE TITLE
fix ownership of files inside docker containers

### ISSUE THREAD

**Issue by vorant94** [vorant94/homelab#9]
currently all files that are created inside of containers are owned by `root` user, hence editing them from host machine requires `sudo` permission

need to fix it, according to claude it can be fixed on volume mounting level with additional settings like this

```yaml
volumes:
  - type: bind
    source: ./host/path
    target: /container/path
    bind:
      create_host_path: true
      uid: 1000
      gid: 1000
```

simultaneously need to transfer ownership of all created this way files so far
